### ISSUE TITLE
#fanout cannot not honor its timeout until the lock is acquired

### ISSUE THREAD

**Issue by cantremember** [AVVS/distributed-callback-queue#4]
this is a tremendous module, @AVVS -- the pubsub aspect you've built is essential to our use case

i tried a sample script with multiple time-staggered jobs to confirm the once-and-once only implemenation of #fanout, as well as the propagation of success and failure results.  it works **great**, with multiple independent processes and everything

then i went and shut down my local Redis server, you know, *to see what would happen*.  the result was an 'unhandledRejection'

```
Unhandled rejection TimeoutError: queue-no-response
    at Object.<anonymous> (~/dlock-test/node_modules/dlock/lib/distributed-callback-queue.js:44:22)
```

i traced it down to the fact that `onJobCompleted` was being invoked with a `TimeoutError`, but `ioredis-lock` was still thrashing about trying to acquire the lock so the #push Promise had not yet resolved.  `onJobCompleted` rejected, its backing `promise` never got returned, so no one was responsible for catching the rejection -- since the caller never received a Promise to #catch it -- and this leads to an 'unhandledRejection'

i have implemented a fix and i am submitting a PR for your review

**Comment by AVVS** [comment]
@cantremember thanks a lot for investigating - will be happy to review a PR :)
